### ISSUE TITLE
Finesse frontend styling

### ISSUE THREAD

**Issue by 0xSEC** [comicrelief/grants-eligibility-form#5]
The checker will be using the pattern lab but there will likely be some tweaks that are needed once implemented. This is the place to capture those.

**Comment by AndyEPhipps** [comment]
@adamthomsCR to use this ticket to raise any design inconsistencies/tweaks/demands etc

**Comment by adamthomsCR** [comment]
**First screen:**
- Body size looks a bit big when compared with the rest of the site. Guidelines say 18px, looks more like 20px
- Remove grey boarder from buttons
- Buttons look bunched up vertically, add some breathing space above. 20/30px
- Center body text here

**General rules:**
- Lessen background grey, try #F0F0F0 
- Concerns me a bit the hover state makes secondary button look the same as primary.. can we style:
Primary: .btn--red Red button
Secondary: .btn--blue Blue button
Thirdaly: .btn--black-ghost Black ghost button

- Bold the font weight on the links
- Also - the website seems to display links with a purple link.. although pattern library says black

- Vertical spacing on most question pages - Separate the preamble and question by 30ish pxls. 


**Email input thingy screen:**
- Can the 'Continue' be in disabled state before input
- Hint text size to be larger - the same as paragraph size?


**On mobile:**
- Buttons to take full width of body
- Body content to align center

**Comment by AndyEPhipps** [comment]
Tweaks are visible here: https://5abbc8a9df9953155845c79a--grants-eligibility-checker.netlify.com/question/3
