### ISSUE TITLE
Improve deploy process

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/grants-eligibility-form#53]
Currently Netlify is set-up to automatically deploy on any merge into master, and this isn't desirable right now. As we're still working on the new version of the Checker that isn't ready to go live yet, I've had to make one huge PR with all of these updates that can only be merged when complete.

As per @pvhee's statement 'we need to do something like feature flags, or rewrite auto deploy'

**Comment by pvhee** [comment]
@AndyEPhipps I think there is no good solution given that we've already progressed this branch into a state we cannot simply add in feature flags.

Therefore, we should probably branch off https://github.com/comicrelief/grants-eligibility-form/pull/52 going forward, and add in tickets for all new features/work we are doing as phase 2. This will allow @0xSEC @adamclark-dev and me to follow & review work.

What do you think?

**Comment by AndyEPhipps** [comment]
Yeah, makes sense to me
